######################################################################
# Automatically generated by qmake (2.01a) mer. mars 21 18:41:05 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += monbouton.h untruc.h
SOURCES += Exo1.cpp monbouton.cpp untruc.cpp
