######################################################################
# Automatically generated by qmake (2.01a) sam. mai 26 13:39:10 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += monbouton.h
SOURCES += Exercice1.cpp monbouton.cpp
