######################################################################
# Automatically generated by qmake (2.01a) mer. mars 28 18:44:15 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += liste.h mamainwindow.h mawidget.h
SOURCES += Exercice2.cpp liste.cpp mamainwindow.cpp mawidget.cpp
