######################################################################
# Automatically generated by qmake (2.01a) mer. mars 28 18:12:48 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mareglette.h
SOURCES += Exercice1.cpp mareglette.cpp
